<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0-android</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <RootNamespace>MouldCheckerApp</RootNamespace>

    <!-- إعدادات تطبيق أندرويد -->
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>

    <ApplicationId>com.company.mouldchecker</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>

    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.102.2" />
    <PackageReference Include="Microsoft.Maui.Controls" Version="8.0.3" />
    <PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.3" />
  </ItemGroup>

  <ItemGroup>
    <MauiXaml Update="App.xaml" />
    <MauiXaml Update="MainPage.xaml" />
  </ItemGroup>
</Project>
